#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug  7 19:44:49 2020

@author: mlaulin
"""

def f2c():
    # Initialize variables
    f = 0
    c = 0

    # Ask user input in Farenheit
    f = input("Enter the temperature in Farenheit: ")
    f = float(f)

    # Convert to Farenheit
    c = (f-32)*5/9
    c = float(c)

    return c

def c2f():
    # Initialize variables
    f = 0
    c = 0

    # Ask user input in Farenheit
    c = input("Enter the temperature in Celsius: ")
    c = float(c)

    # Convert to Farenheit
    f = (c*(9/5))+32
    f = float(f)

    return f

# Get user input
i = 0
i = input("Enter 1 for converting from Farenheit to Celsius and enter 2 for converting from Celsius to Farenheit: ")
i = int(i)
v = 0

if (i == 1):
    v = f2c()
    v = round(v, 2)
    print ("The temperature in Celsius is: {}".format(v))
if (i == 2):
    v = c2f()
    v = round(v, 2)
    print ("The temperature in Farenheit is: {}".format(v))


